import { configureStore } from "@reduxjs/toolkit";
// import reducer generated by the topics slice and add to the app's store
import topicsReducer from "../features/topics/topicsSlice";

export default configureStore({
  reducer: {
    topics: topicsReducer,
  },
});
